version: 'lts'
services:
  api:
    # command: python manage.py runserver 0.0.0.0:8000
    build: .
    container_name: 'api_c'
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - /code/venv