# Generated by Django 4.1 on 2022-09-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovieFeedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_title", models.CharField(max_length=500)),
                ("movie_image", models.TextField()),
                ("movie_description", models.TextField()),
                ("movie_genre", models.CharField(max_length=20)),
                ("movie_link_id", models.CharField(max_length=20)),
                ("movie_rating", models.FloatField()),
            ],
        ),
    ]
