# Generated by Django 4.1 on 2022-09-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CinemaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cinema_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MovieItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_title", models.CharField(max_length=500)),
                ("movie_image", models.TextField()),
                ("movie_description", models.TextField()),
                ("movie_genre", models.CharField(max_length=20)),
                ("movie_link_id", models.CharField(max_length=20)),
                ("movie_rating", models.FloatField()),
                (
                    "cinema_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies_api.cinemaitem",
                    ),
                ),
            ],
        ),
    ]
