# Generated by Django 4.1 on 2022-09-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieitem",
            old_name="cinema_id",
            new_name="cinema",
        ),
    ]
