# Generated by Django 4.1 on 2022-09-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CinemaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cinema_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name="MovieFeedItem",
            new_name="MovieItem",
        ),
    ]
