# Generated by Django 4.1 on 2022-09-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies_api", "0002_cinemaitem_rename_moviefeeditem_movieitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieitem",
            name="cinema_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies_api.cinemaitem",
                to_field="cinema_name",
            ),
        ),
        migrations.AlterField(
            model_name="cinemaitem",
            name="cinema_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
