# Generated by Django 4.1 on 2022-09-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies_api", "0002_rename_cinema_id_movieitem_cinema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieitem",
            name="cinema",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="movies_api.cinemaitem",
            ),
        ),
    ]
