# Generated by Django 4.1 on 2022-09-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies_api", "0003_movieitem_cinema_name_alter_cinemaitem_cinema_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieitem",
            name="cinema_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies_api.cinemaitem",
            ),
        ),
    ]
