# Generated by Django 4.1 on 2022-09-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_api", "0003_alter_movieitem_cinema"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinemaitem",
            name="cinema_link",
            field=models.CharField(default="hi", max_length=50),
            preserve_default=False,
        ),
    ]
