# Generated by Django 4.1 on 2022-09-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies_api", "0004_alter_movieitem_cinema_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieitem",
            name="cinema_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies_api.cinemaitem"
            ),
        ),
    ]
