# Generated by Django 4.1 on 2022-09-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies_api", "0005_alter_movieitem_cinema_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieitem",
            old_name="cinema_name",
            new_name="cinema_id",
        ),
    ]
