# Generated by Django 4.1 on 2022-09-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_api", "0006_rename_cinema_name_movieitem_cinema_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinemaitem",
            name="cinema_name",
            field=models.CharField(max_length=50),
        ),
    ]
