# Generated by Django 4.1 on 2022-09-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies_api", "0007_alter_cinemaitem_cinema_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieitem",
            name="cinema_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies_api.cinemaitem",
            ),
        ),
    ]
