# Generated by Django 4.1 on 2022-09-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies_api", "0008_alter_movieitem_cinema_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieitem",
            name="cinema_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies_api.cinemaitem",
            ),
            preserve_default=False,
        ),
    ]
