# Generated by Django 4.1 on 2022-09-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies_api", "0009_alter_movieitem_cinema_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movieitem",
            name="cinema_id",
        ),
    ]
